name: "Coverage"

on: [push, pull_request]

jobs:
  job:
    name: "Code coverage"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install cmake"
      uses: lukka/get-cmake@latest

    - name: "Install lcov"
      run: sudo apt-get install lcov

    - name: "Configure"
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_COVERAGE=ON

    - name: "Run code coverage"
      run: |
        cd build
        make coverage

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1.0.7
      with:
        file: build/coverage.info

    - name: "Upload coverage to Coveralls"
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: build/coverage.info
