name: "Lint"

on:
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "clang-tidy / cppcheck"
        uses: smay1613/clang-tidy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
