name: "Lint"

on:
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "clang-tidy check"
        uses: muxee/clang-tidy-action@0.0.1-rc1
